// types/address.ts

export interface Address {
  id?: number; // Optional, as it will be generated by the backend for new addresses
  fullName: string;
  phone: string;
  pincode: string;
  state: string;
  city: string;
  addressLine: string;
  landmark?: string; // Optional field
}
