import type { Metadata } from "next";
// Import Josefin Sans along with your existing fonts
import { Geist, Geist_Mono, Josefin_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ServersideComponent/Navbar/NavbarComponent";
import ReduxProviderWrapper from "@/providers/ReduxProviderWrapper";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Define Josefin Sans
const josefinSans = Josefin_Sans({
  variable: "--font-josefin-sans", // Define a CSS variable for Josefin Sans
  subsets: ["latin"],
  display: "swap", // Recommended for better font loading
});

export const metadata: Metadata = {
  title: "Cosmectics",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // Add the Josefin Sans variable to the body's className
        className={`${geistSans.variable} ${geistMono.variable} ${josefinSans.variable} antialiased`}
      >
        <ReduxProviderWrapper>
        <Toaster position="top-right" />
          <Navbar />
          <main className="pt-0">{children}</main>
        </ReduxProviderWrapper>
      </body>
    </html>
  );
}
